// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoboxg-BNkUg9d0698DvvgDYLr2-02UVY',
    appId: '1:551327065763:web:da1adb1b6c6bd059538116',
    messagingSenderId: '551327065763',
    projectId: 'fire-base-21101',
    authDomain: 'fire-base-21101.firebaseapp.com',
    storageBucket: 'fire-base-21101.firebasestorage.app',
    measurementId: 'G-JZDZX1TG82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XfJS5WMykgMQEVdyWFR5fvyJdccZm2Q',
    appId: '1:551327065763:android:a552758d2f0ce9a0538116',
    messagingSenderId: '551327065763',
    projectId: 'fire-base-21101',
    storageBucket: 'fire-base-21101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2B-LAjEK4bsRbvf09wrRhN1zRCLOp0qs',
    appId: '1:551327065763:ios:76c53834dfc02d2f538116',
    messagingSenderId: '551327065763',
    projectId: 'fire-base-21101',
    storageBucket: 'fire-base-21101.firebasestorage.app',
    iosBundleId: 'com.fire-base.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2B-LAjEK4bsRbvf09wrRhN1zRCLOp0qs',
    appId: '1:551327065763:ios:76c53834dfc02d2f538116',
    messagingSenderId: '551327065763',
    projectId: 'fire-base-21101',
    storageBucket: 'fire-base-21101.firebasestorage.app',
    iosBundleId: 'com.fire-base.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoboxg-BNkUg9d0698DvvgDYLr2-02UVY',
    appId: '1:551327065763:web:ee74f22000c8c7bf538116',
    messagingSenderId: '551327065763',
    projectId: 'fire-base-21101',
    authDomain: 'fire-base-21101.firebaseapp.com',
    storageBucket: 'fire-base-21101.firebasestorage.app',
    measurementId: 'G-ZP5MQYS5PV',
  );
}
